### ISSUE TITLE
Where is this gist url?

### ISSUE THREAD

**Issue by tongzh** [pact-foundation/pact-foundation.github.io#24]
Excuse me, where is the url of this gist mentioned in [Why Pact may not be the best tool for testing pass through APIs?](https://github.com/pact-foundation/pact-foundation.github.io/blob/test/faq/README.md#why-pact-may-not-be-the-best-tool-for-testing-pass-through-apis) : 
> Check out this **gist** for an example of how to use the Pact contract generation and matching code to test non-HTTP communications.

**Comment by mefellows** [comment]
I think it is https://gist.github.com/bethesque/0ee446a9f93db4dd0697

Sorry, looks like we need to fix the link!

**Comment by bethesque** [comment]
Fixed.
