### ISSUE TITLE
[Question] About the last several questions of FAQ section

### ISSUE THREAD

**Issue by tongzh** [pact-foundation/pact-foundation.github.io#25]
Hi there, 

I am translating the pact documents to Chinese version with @wldandan. But in the FAQ section, about the last several questions from [here](https://docs.pact.io/faq/#how-to-prevent-a-consumer-from-deploying-with-an-invalid-contract), I can not find the source text either in `gitbook` branch or `master` branch of this repo. The repo only contains those questions before this question I mentioned. Could you help find out where are the sources of the `docs.pact.io` site ? Thanks.

**Comment by tongzh** [comment]
Is the latest content of [https://docs.pact.io/](https://docs.pact.io/) synced using the [`test`](https://github.com/pact-foundation/pact-foundation.github.io/tree/test) branch?

**Comment by bethesque** [comment]
@mefellows you're across the gitbook stuff aren't you?

**Comment by bethesque** [comment]
@tongzh yes, I believe it does use the test branch.

**Comment by mefellows** [comment]
Yep, it sure is. we're probably about due to change that, we'll let you know if we do though :)

**Comment by tongzh** [comment]
Thanks @mefellows , to keep the consistency with [docs.pact.io](docs.pact.io), we're using the `test` branch for translating.
