### ISSUE TITLE
About the interchanged link

### ISSUE THREAD

**Issue by tongzh** [pact-foundation/pact-foundation.github.io#27]
Hi @mefellows ,

As the [Chinese version](https://www.pact.net.cn/) of the pact documents has been published, we have put a link button to the [English version](https://docs.pact.io) of documents site on the top of Chinese site. Can you also please put a link button to the Chinese site on the top of English site as well ? That'll be fine for Chinese developers to find the entry of Chinese site.
A recommended way to implement that is to add a `toolbar-button` plugin to gitbook, which means you can put the following config into `book.json` file:
```json
{
    "plugins": [
        "toolbar-button"
    ],
    "pluginsConfig": {
        "toolbar-button": {
            "icon": "fa-globe",
            "label": "中",
            "url": "https://www.pact.net.cn"
        }
    }
}
``` 
Thanks in advance! If there're any other ideas of how to do that, please let me know.

**Comment by mefellows** [comment]
Just pushed out this toolbar button link - should do the trick!
